### ISSUE TITLE
I'm also running into this issue. It appears there's no way to search notes by content?

### ISSUE THREAD

**Issue by brent85** [hackmdio/status.hackmd.io#47]
I'm also running into this issue. It appears there's no way to search notes by content?

_Originally posted by @jcorert in https://github.com/hackmdio/codimd/issues/1819#issuecomment-1913758470_

**Comment by jackycute** [comment]
> ```
>           I'm also running into this issue. It appears there's no way to search notes by content?
> ```
> 
> _Originally posted by @jcorert in [hackmdio/codimd#1819 (comment)](https://github.com/hackmdio/codimd/issues/1819#issuecomment-1913758470)_

Hi @brent85,
I think you open issue in wrong repo.

**Comment by brent85** [comment]
@a60814billy

**Comment by brent85** [comment]
@brent85

**Comment by brent85** [comment]
> ```
>           I'm also running into this issue. It appears there's no way to search notes by content?
> ```
> 
> _Originally posted by @jcorert in [hackmdio/codimd#1819 (comment)](https://github.com/hackmdio/codimd/issues/1819#issuecomment-1913758470)_

**Comment by brent85** [comment]
[bookmarks.csv](https://github.com/hackmdio/status.hackmd.io/files/14100876/bookmarks.csv)
